import "@/styles/reset.css";
import "@/styles/global.css";
import "@/styles/variable.css";

import { mainFont } from "@/libs/font";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "AI Project",
  description: "Generated by selin yılmaz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mainFont.className}>
      <body className="layout">
        {children}
        <Footer />
        <div className="overlay" />
      </body>
    </html>
  );
}
